"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
type Booking={id:string;reference:string;customer_name:string;phone:string;court:string;booking_date:string;start_time:string;end_time:string;total_amount:number;booking_status:string;payment_status:string};
export default function Admin(){
 const [rows,setRows]=useState<Booking[]>([]),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[logged,setLogged]=useState(false),[err,setErr]=useState("");
 async function login(e:React.FormEvent){e.preventDefault();setErr("");const {error}=await supabase.auth.signInWithPassword({email,password});if(error){setErr(error.message);return;}setLogged(true);}
 async function load(){const {data,error}=await supabase.from("bookings").select("id,reference,customer_name,phone,court,booking_date,start_time,end_time,total_amount,booking_status,payment_status").order("booking_date",{ascending:true});if(error)setErr(error.message);else setRows((data||[]) as Booking[]);}
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session)setLogged(true);});},[]);
 useEffect(()=>{if(logged)load();},[logged]);
 async function update(id:string,field:"booking_status"|"payment_status",value:string){const {error}=await supabase.from("bookings").update({[field]:value}).eq("id",id);if(error)setErr(error.message);else load();}
 if(!logged)return <main className="wrap"><a href="/">← Home</a><section className="card section" style={{maxWidth:480,margin:"50px auto"}}><h1>Admin Login</h1><form onSubmit={login}><div className="field"><label>Email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="field"><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></div><button className="submit">Log in</button>{err&&<div className="error">{err}</div>}</form></section></main>;
 return <main className="wrap"><nav className="nav"><div className="logo"><span className="net">Net</span><span className="zone">Zone</span> Admin</div><button className="pill" onClick={async()=>{await supabase.auth.signOut();setLogged(false);}}>Log out</button></nav><h1>Bookings</h1>{err&&<div className="error">{err}</div>}<div className="card" style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:14}}><thead><tr>{["Ref","Customer","Court","Date","Time","Amount","Booking","Payment"].map(x=><th key={x} style={{textAlign:"left",padding:12,borderBottom:"1px solid #ddd"}}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}>{[r.reference,`${r.customer_name} · ${r.phone}`,r.court,r.booking_date,`${r.start_time}–${r.end_time}`,`₱${r.total_amount}`,null,null].map((v,i)=>i<6?<td key={i} style={{padding:12,borderBottom:"1px solid #eee"}}>{v}</td>:null)}<td style={{padding:10}}><select value={r.booking_status} onChange={e=>update(r.id,"booking_status",e.target.value)}>{["PENDING","CONFIRMED","CANCELLED","COMPLETED","NO_SHOW"].map(x=><option key={x}>{x}</option>)}</select></td><td style={{padding:10}}><select value={r.payment_status} onChange={e=>update(r.id,"payment_status",e.target.value)}>{["PENDING_VERIFICATION","PAID","REJECTED","REFUNDED"].map(x=><option key={x}>{x}</option>)}</select></td></tr>)}</tbody></table>{!rows.length&&<p className="note">No bookings yet.</p>}</div></main>;
}